### ISSUE TITLE
Streamline installation process

### ISSUE THREAD

**Issue by messersc** [Oshlack/Clinker#8]
Hi,

the current installation is a little cumbersome and I think we can make it easier with little effort. The reason is that all the software that gets installed outside of conda right now if you follow the wiki page is also available through conda. In the end, of course it would be very nice if Clinker itself would also make to bioconda.

Short-term, we can aim for an `environment.yaml` file (https://conda.io/docs/user-guide/tasks/manage-environments.html#create-env-file-manually).

Note that the conda `r` channel is not needed anymore, if we use the multichannel `defaults` (https://github.com/conda/conda/issues/7695#issuecomment-416350450)

For example:

```yaml
name: clinker
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python=2.7
  - star=2.5.3a
  - samtools
  - bpipe
  - bioconductor-gviz # pulls biomart, R
```

The above is untested, I'll let you know how it goes and then we can decide what the best course of action is.

Clemens
